name: goodfood
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State
  flutter_bloc: 8.1.1
  provider: 6.0.3

  # Service
  dio: 4.0.6
  path_provider: 2.0.0
  path: 1.8.2

  # Value Equality
  equatable: 2.0.5

  # Database
  drift: 2.1.0
  sqlite3_flutter_libs: 0.5.0

  # More
  # dartz: 0.10.1
  carousel_slider: 4.1.1
  flutter_screenutil: 5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  # More
  mockito: 5.3.0
  drift_dev: 2.1.0
  build_runner: 2.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
